print('Hello, esse é um teste do repositorio do trabalho final de apc')
print('Faca um commit de uma nova linha aqui em baixo com seu nome se vc tem acesso a fazer alteracoes no codigo')
print('André Em.')
print('Ricardo tem acesso e esta testando o commit direto no master')
print("teste matheus pelo vscode")